version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: x86

environment:
  matrix:
  - solution_name: /dependencies/minhook/build/VC15/Umihara Kawase Loader.sln
  - solution_name: Umihara Kawase Loader.sln

build_script:
  - msbuild %solution_name%
